name: Unit Tests

on: [push]

jobs:
  test:
    name: Test on php ${{ matrix.php_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php_version: [7.1, 7.2, 7.3, 7.4]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install extensions
      run: pecl install -f msgpack && pecl install -f igbinary && php -m

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run test
